import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "@/trpc/react";
import InfluencerCard from "./_components/influencer/influencer-card";
import SuggestedCard from "./_components/influencer/suggested-card";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const influencer = {
    "_id" : "661e45ed85a6eea351ffdf81",
    "name" : "Juventus",
    "username" : "juventus",
    "bio" : "An Italian Icon since 1897 ⚪️⚫️ Hit follow and be part of the journey! More 🏃‍♀️content ➡️ @juventuswomen",
    "avatar" : "https://cdn1.picuki.com/hosted-by-instagram/q/yep6IPkO1EBGZyPbcMUVwOZVj6JwQAQ=.jpeg",
    "stats" : {
        "postsCount" : "16,503",
        "followerCount" : "60,426,963",
        "followingCount" : "75"
    },
    "platform" : "Instagram",
    "contact" : {
        "email" : [

        ],
        "phone" : [

        ],
        "url" : [

        ]
    },
    "categories" : [
        "Sports",
        "Soccer",
        "Football"
    ],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        {/* <TRPCReactProvider>{children}</TRPCReactProvider> */}
        <SuggestedCard influencer={influencer} />
      </body>
    </html>
  );
}
